mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: false
proxies:
- name: Singapore 1
  type: vmess
  server: sg-1.stunnel.cc
  port: 8443
  uuid: 35342035-3520-4533-a031-303120353120
  alterId: 0
  cipher: auto
  network: ws
  udp: true
  ws-opts:
    path: /ws
    headers:
      Host: sg-1.stunnel.cc
  tls: true
  skip-cert-verify: true
- name: Singapore 2
  type: trojan
  server: sg10.vpnjantit.com
  port: 8443
  network: tcp
  udp: true
  skip-cert-verify: true
  password: Piyash665-vpnjantit.com
  tls: true
- name: Singapore 3
  type: vmess
  server: sg10.vpnjantit.com
  port: 10000
  uuid: 151e5b18-7168-11f1-8429-1fae7863314c
  alterId: 0
  cipher: auto
  network: ws
  udp: true
  ws-opts:
    path: /vpnjantit
- name: Bangladesh 2
  type: vmess
  server: bd1.vpnjantit.com
  port: 10000
  uuid: ef421112-757e-11f1-b399-525401f40bae
  alterId: 0
  cipher: auto
  network: ws
  udp: true
  ws-opts:
    path: /vpnjantit
proxy-groups:
- name: All-In-One-Group
  type: select
  proxies:
  - Singapore 1
  - Singapore 2
  - Singapore 3
  - Bangladesh 2
  - DIRECT
rules:
- MATCH,All-In-One-Group
