mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: false
proxies:
- name: Saudi Arabia 1
  type: vless
  server: sau2.vpnjantit.com
  port: 10002
  network: ws
  udp: true
  uuid: c3fddfc0-6ad6-11f1-9647-00163c5f28ea
  tls: true
  ws-opts:
    path: /vpnjantit
    headers:
      Host: telegram.org
  sni: telegram.org
  skip-cert-verify: true
- name: United States 1
  type: trojan
  server: usa9.vpnjantit.com
  port: 8443
  network: tcp
  udp: true
  password: piyash99-vpnjantit.com
  tls: true
- name: Bangladesh 4
  type: vmess
  server: bd1.vpnjantit.com
  port: 10000
  uuid: 5e9420aa-6b52-11f1-8125-525401f40bae
  alterId: 0
  cipher: auto
  network: ws
  udp: true
  ws-opts:
    path: /vpnjantit
- name: Singapore
  type: vmess
  server: sg-1.stunnel.cc
  port: 8443
  uuid: 34382039-3920-4937-a035-362035342039
  alterId: 0
  cipher: auto
  network: ws
  udp: true
  ws-opts:
    path: /ws
    headers:
      Host: sg-1.stunnel.cc
  tls: true
- name: Singapore 1
  type: vmess
  server: sg-4.stunnel.cc
  port: 8443
  uuid: 34392031-3031-4031-b032-203130302031
  alterId: 0
  cipher: auto
  network: ws
  udp: true
  ws-opts:
    path: /ws
    headers:
      Host: sg-4.stunnel.cc
  tls: true
  skip-cert-verify: true
- name: Brazil 1
  type: vmess
  server: br1.vpnjantit.com
  port: 10000
  uuid: bb4f0b0e-6c4a-11f1-b06c-00163c976cf7
  alterId: 0
  cipher: auto
  network: ws
  udp: true
  ws-opts:
    path: /vpnjantit
proxy-groups:
- name: All-In-One-Group
  type: select
  proxies:
  - Saudi Arabia 1
  - United States 1
  - Bangladesh 4
  - Singapore
  - Singapore 1
  - Brazil 1
  - DIRECT
rules:
- MATCH,All-In-One-Group
