mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: false
proxies:
- name: Bangladesh 1
  type: vmess
  server: bd1.vpnjantit.com
  port: 10000
  uuid: 7768221c-6944-11f1-815e-525401f40bae
  alterId: 0
  cipher: auto
  network: ws
  ws-opts:
    path: /vpnjantit
  udp: true
- name: Bangladesh 2
  type: vmess
  server: bd2.vpnjantit.com
  port: 10000
  uuid: 7768221c-6944-11f1-815e-525401f40bbe
  alterId: 0
  cipher: auto
  network: ws
  ws-opts:
    path: /vpnjantit
  udp: true
- name: Singapore
  type: vmess
  server: sg3.vpnjantit.com
  port: 10000
  uuid: 5f407ac8-6ac9-11f1-a596-d7a5af4e4570
  alterId: 0
  cipher: auto
  network: ws
  ws-opts:
    path: /vpnjantit
  udp: true
- name: Singapore 1
  type: trojan
  server: sg11.vpnjantit.com
  port: 8443
  network: tcp
  udp: true
  password: Piyash686-vpnjantit.com
  sni: telegram.org
  tls: true
  servername: telegram.org
- name: Saudi Arabia 1
  type: vless
  server: sau2.vpnjantit.com
  port: 10002
  network: ws
  udp: true
  uuid: c3fddfc0-6ad6-11f1-9647-00163c5f28ea
  tls: true
  ws-opts:
    path: /vpnjantit
    headers:
      Host: telegram.org
  sni: telegram.org
  skip-cert-verify: true
- name: United States 1
  type: trojan
  server: usa9.vpnjantit.com
  port: 8443
  network: tcp
  udp: true
  password: piyash99-vpnjantit.com
  tls: true
proxy-groups:
- name: All-In-One-Group
  type: select
  proxies:
  - Bangladesh 1
  - Bangladesh 2
  - Singapore
  - Singapore 1
  - Saudi Arabia 1
  - United States 1
  - DIRECT
rules:
- MATCH,All-In-One-Group
